### ISSUE TITLE
Works perfect on PyTorch 2.3.0 but not 2.2.2

### ISSUE THREAD

**Issue by zhenyuanzhou** [kijai/ComfyUI-segment-anything-2#12]
Any possibility of refining the code so as to be compatible with a lower PyTorch version, otherwise I need to sacrifice some nodes? Many thanks.

**Comment by Quasimondo** [comment]
Which nodes would that be? I am running comfy with 2.4.0 and have no compatibility issues with any custom node packages.

**Comment by zhenyuanzhou** [comment]
> Which nodes would that be? I am running comfy with 2.4.0 and have no compatibility issues with any custom node packages.

ComfyUI-BiRefNet-ZHO, doesn't work after upgrading the PyTorch. I would appreciate if you could help with the issue.

Could not run 'torchvision::deform_conv2d' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::deform_conv2d' is only available for these backends: [CPU, Meta, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

**Comment by zhenyuanzhou** [comment]
This issue stands still even if I change back to the original version of PyTorch.

**Comment by zhenyuanzhou** [comment]
Fixed after another try at reinstalling
