### ISSUE TITLE
Not able to loead background image

### ISSUE THREAD

**Issue by bejaranoo** [kijai/ComfyUI-segment-anything-2#14]
Hello, thanks for the work, I'm not able to load the image to accurately select the spline points, otherwise everything works great

![image](https://github.com/user-attachments/assets/3fc38c2a-9b93-4e85-93fd-9ccbb01e921d)

**Comment by ycyy** [comment]
on chrome i choose an image,it keeps prompting to select an image

**Comment by bejaranoo** [comment]
> on chrome i choose an image,it keeps prompting to select an image

thats exactly what happens to me but on firefox :P

**Comment by kijai** [comment]
You can test my work in progress PointsEditor node instead, it supports copy/paste and drag&drop images to it, should be better:

https://github.com/user-attachments/assets/17192268-3525-411a-a73f-f8e5050747cc

You can get it by updating KJNodes.

**Comment by bejaranoo** [comment]
the PointsEditor node is more stable and usefull, since it can take the image as input, thanks!
