### ISSUE TITLE
MPS and CPU Devices not working on M1 Macbook

### ISSUE THREAD

**Issue by studiosobu-MK** [kijai/ComfyUI-segment-anything-2#25]
As I am on an M1 I cannot use cuda as a device, but every time I try to switch the device to mps or cpu I get the following errors: 

MPS: "Error occurred when executing Sam2Segmentation: User specified an unsupported autocast device_type 'mps'"

CPU: "Error occurred when executing Sam2Segmentation: Torch not compiled with CUDA enabled File "

<img width="1143" alt="Screenshot 2024-08-02 at 10 40 50" src="https://github.com/user-attachments/assets/64ed0c77-9595-4cce-9aba-1febeeb034ec">

**Comment by kijai** [comment]
Which torch version do you have? There were still some hardcoded .cuda calls that I now replaced, but also  the attention code they had was cuda only originally, I did update it to use newer torch code, but that only runs if you have torch 2.3.1 minimum.

**Comment by studiosobu-MK** [comment]
Thank you very much for updating it, now it runs smoothly! Torch Version is 2.4.0, so it was probably an issue with the hardcoded .cuda calls!

**Comment by rayanarman** [comment]
I'm using M1 MAX and I've just pulled your latest update but am getting torch autocast not support on device 'mps' errors. If I set it to cpu it will run but not mps?

**Comment by kijai** [comment]
> I'm using M1 MAX and I've just pulled your latest update but I am getting torch autocast is not supported on device 'mps' errors. If I set it to cpu it will run but not mps?

Can you update and try again now?

**Comment by rayanarman** [comment]
thanks for the quick response... i have a new error now:

Error occurred when executing Sam2Segmentation:
repeat(): Not supported for complex yet!

File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/sam2_video_predictor.py", line 651, in propagate_in_video
current_out, pred_masks = self._run_single_frame_inference(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/sam2_video_predictor.py", line 794, in _run_single_frame_inference
current_out = self.track_step(
^^^^^^^^^^^^^^^^
File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/modeling/sam2_base.py", line 744, in track_step
pix_feat_with_mem = self._prepare_memory_conditioned_features(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/modeling/sam2_base.py", line 653, in _prepare_memory_conditioned_features
pix_feat_with_mem = self.memory_attention(
^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rayanarman/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rayanarman/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1727, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/modeling/memory_attention.py", line 155, in forward
output = layer(

**Comment by rayanarman** [comment]
just to add, i have Name: torch Version: 2.5.0.dev20240715

**Comment by kijai** [comment]
> thanks for the quick response... i have a new error now:
> 
> Error occurred when executing Sam2Segmentation: repeat(): Not supported for complex yet!
> 
> File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/sam2_video_predictor.py", line 651, in propagate_in_video current_out, pred_masks = self._run_single_frame_inference( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/sam2_video_predictor.py", line 794, in _run_single_frame_inference current_out = self.track_step( ^^^^^^^^^^^^^^^^ File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/modeling/sam2_base.py", line 744, in track_step pix_feat_with_mem = self._prepare_memory_conditioned_features( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/modeling/sam2_base.py", line 653, in _prepare_memory_conditioned_features pix_feat_with_mem = self.memory_attention( ^^^^^^^^^^^^^^^^^^^^^^ File "/Users/rayanarman/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/rayanarman/anaconda3/envs/comfyui/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1727, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/rayanarman/anaconda3/envs/comfyui/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/sam2/modeling/memory_attention.py", line 155, in forward output = layer(

Yeah sorry I have no idea, some operation is just not supported on mps. The original SAM2 code was cuda only and it doesn't seem like they have taken mps into account at all.

**Comment by rayanarman** [comment]
hey, thanks for trying! I tried rewriting the .repeat calls replacing with .expand and reshaping but the errors just kept moving downstream and I gave up! I've got it working on CPU so that's okay for now.
