### ISSUE TITLE
 No module named 'torch.nn.attention' ,Does this not support PyTorch version 2.1.2 ？

### ISSUE THREAD

**Issue by Erwin11** [kijai/ComfyUI-segment-anything-2#5]
###  No module named 'torch.nn.attention' 

![Torch version 2 1 2+cu118 ](https://github.com/user-attachments/assets/2fd23778-4b80-4329-8c86-5766edbc264f)

It seems that PyTorch version 2.1.2 is not supported.
If SAM2 requires PyTorch 2.3.1, I will try updating the PyTorch version later.

**Comment by yangbiao11** [comment]
that is version not compatible
I deal this way,in path to file:sam2/modeling/sam/transformer.py :

#from torch.nn.attention import SDPBackend, sdpa_kernel
from torch.nn.functional import scaled_dot_product_attention as sdpa_kernel
from torch._C import _SDPBackend as SDPBackend

that is work for me

**Comment by kijai** [comment]
I can add that as a workaround if it really works, the original minimum was 2.3.1 and I've personally not used older ones for months.

**Comment by guahunyo** [comment]
> I can add that as a workaround if it really works, the original minimum was 2.3.1 and I've personally not used older ones for months.如果它确实有效，我可以添加一个解决方法，原始的最低版本是 2.3.1，我个人几个月都没有使用过旧的。

Because I am cu121, and flash-attn cannot find the whl of torch2.3 cu121, so I used the whl of torch2.1+cu121

**Comment by guahunyo** [comment]
> > I can add that as a workaround if it really works, the original minimum was 2.3.1 and I've personally not used older ones for months.如果它确实有效，我可以添加一个解决方法，原始的最低版本是 2.3.1，我个人几个月都没有使用过旧的。
> 
> Because I am cu121, and flash-attn cannot find the whl of torch2.3 cu121, so I used the whl of torch2.1+cu121因为我是 cu121，flash-attn 找不到 torch2.3 cu121 的 wwl，所以我使用了 torch2.1+cu121 的 whl

If I don't change to cu121, once I change to torch2.3, I won't be able to use flash-attn.

**Comment by kijai** [comment]
> > I can add that as a workaround if it really works, the original minimum was 2.3.1 and I've personally not used older ones for months.如果它确实有效，我可以添加一个解决方法，原始的最低版本是 2.3.1，我个人几个月都没有使用过旧的。
> 
> Because I am cu121, and flash-attn cannot find the whl of torch2.3 cu121, so I used the whl of torch2.1+cu121

There are flash_attn wheels that work with 2.3.1 here:

https://github.com/bdashore3/flash-attention/releases

I also added workaround to these nodes that should maybe work with old torch too now.

**Comment by guahunyo** [comment]
> > > I can add that as a workaround if it really works, the original minimum was 2.3.1 and I've personally not used older ones for months.如果它确实有效，我可以添加一个解决方法，原始的最低版本是 2.3.1，我个人几个月都没有使用过旧的。
> > 
> > 
> > Because I am cu121, and flash-attn cannot find the whl of torch2.3 cu121, so I used the whl of torch2.1+cu121
> 
> There are flash_attn wheels that work with 2.3.1 here:
> 
> https://github.com/bdashore3/flash-attention/releases
> 
> I also added workaround to these nodes that should maybe work with old torch too now.

I saw this link from your lumina node, but the torch2.3 in it does not have cu121.

**Comment by Erwin11** [comment]
> that is version not compatible I deal this way,in path to file:sam2/modeling/sam/transformer.py :
> 
> #from torch.nn.attention import SDPBackend, sdpa_kernel from torch.nn.functional import scaled_dot_product_attention as sdpa_kernel from torch._C import _SDPBackend as SDPBackend
> 
> that is work for me

It does not work for me.
![change](https://github.com/user-attachments/assets/7390f285-b56d-4485-99de-8f25ab6f2295)

florence_segment_2  has 2 errors：
![example-1error-1](https://github.com/user-attachments/assets/612e4f51-b6bf-49fb-9bff-beed9299d17f)
![example-1error-2](https://github.com/user-attachments/assets/5e278bd5-93f7-48d1-b37d-708d1695b832)

points_segment_example has 1 errors:
![example2error](https://github.com/user-attachments/assets/3803c57c-b04a-471f-aa10-ca8e120dfd13)

name 'SDPBackend' is not defined ,  I guess it's because of what i have changed  "#from torch.nn.attention import SDPBackend, sdpa_kernel".
I'm still with pytorch 2.1.2 yet.

**Comment by kijai** [comment]
> > > > I can add that as a workaround if it really works, the original minimum was 2.3.1 and I've personally not used older ones for months.如果它确实有效，我可以添加一个解决方法，原始的最低版本是 2.3.1，我个人几个月都没有使用过旧的。
> > > 
> > > 
> > > Because I am cu121, and flash-attn cannot find the whl of torch2.3 cu121, so I used the whl of torch2.1+cu121
> > 
> > 
> > There are flash_attn wheels that work with 2.3.1 here:
> > https://github.com/bdashore3/flash-attention/releases
> > I also added workaround to these nodes that should maybe work with old torch too now.
> 
> I saw this link from your lumina node, but the torch2.3 in it does not have cu121.

The minor cuda version doesn't need to match, it still works.

**Comment by kijai** [comment]
> > that is version not compatible I deal this way,in path to file:sam2/modeling/sam/transformer.py :
> > #from torch.nn.attention import SDPBackend, sdpa_kernel from torch.nn.functional import scaled_dot_product_attention as sdpa_kernel from torch._C import _SDPBackend as SDPBackend
> > that is work for me
> 
> It does not work for me. ![change](https://private-user-images.githubusercontent.com/6300501/353809634-7390f285-b56d-4485-99de-8f25ab6f2295.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY0NDgsIm5iZiI6MTcyMjQyNjE0OCwicGF0aCI6Ii82MzAwNTAxLzM1MzgwOTYzNC03MzkwZjI4NS1iNTZkLTQ0ODUtOTlkZS04ZjI1YWI2ZjIyOTUuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTE0MjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTliZjZmZGU3YTE3YTYyNmI4YTg0M2JhNDg4NmMxZmMxMTkxYzM4NGY2OGU2Zjc3ZmM0MTM1NTJkYWNmYWYwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2lXlH8ZY3I1UoMGypvPtAi2bC6y8yw4FiEyt7L2uoSY)
> 
> florence_segment_2 has 2 errors： ![example-1error-1](https://private-user-images.githubusercontent.com/6300501/353809687-612e4f51-b6bf-49fb-9bff-beed9299d17f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY0NDgsIm5iZiI6MTcyMjQyNjE0OCwicGF0aCI6Ii82MzAwNTAxLzM1MzgwOTY4Ny02MTJlNGY1MS1iNmJmLTQ5ZmItOWJmZi1iZWVkOTI5OWQxN2YuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTE0MjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjk4YWQ1NTM5ZTNlYTU5NWY0MThkYTRmMzViZWRlODI4MmE1NzcwZmRjODFiMGJlNDAxMTlmNTUzZmE1NWZjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lFWgt-vNdyWKqGAMNmFcwa6hGouinUViCJu3dJkorfw) ![example-1error-2](https://private-user-images.githubusercontent.com/6300501/353809702-5e278bd5-93f7-48d1-b37d-708d1695b832.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY0NDgsIm5iZiI6MTcyMjQyNjE0OCwicGF0aCI6Ii82MzAwNTAxLzM1MzgwOTcwMi01ZTI3OGJkNS05M2Y3LTQ4ZDEtYjM3ZC03MDhkMTY5NWI4MzIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTE0MjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E4MDgxMjMwOTM2MzRhMWI3YTI0OGNjOWM1ZTg3ZWY1YzIxNWZjM2NjZDQxZjg5ZGUxMDExODU5ZjQwYTc5NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dOffPZm452H8cv-aYnUfVcrc2Fn01-1qLakG3rsPeWU)
> 
> points_segment_example has 1 errors: ![example2error](https://private-user-images.githubusercontent.com/6300501/353809720-3803c57c-b04a-471f-aa10-ca8e120dfd13.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjY0NDgsIm5iZiI6MTcyMjQyNjE0OCwicGF0aCI6Ii82MzAwNTAxLzM1MzgwOTcyMC0zODAzYzU3Yy1iMDRhLTQ3MWYtYWExMC1jYThlMTIwZGZkMTMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMTE0MjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTk2NzkyM2FhN2EzNjgzOWJkOGU0Y2FhNTA3YjhiODAyYzFiMWU3ZjExOWQyMjI4MmQyY2U2ZDNkYWY1MDAwYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.t9bqcwv6WuhrYvQ47GE9aLn4AkQ2CNecBofczSXWd5Y)
> 
> name 'SDPBackend' is not defined , I guess it's because of what i have changed "#from torch.nn.attention import SDPBackend, sdpa_kernel". I'm still with pytorch 2.1.2 yet.

If that code in the screenshot is what you're running, you only removed the import but didn't add the old one. Anyway it shouldn't be necessary in the latest version anymore.
